apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp-namespace
spec:
  selector:
    app: employees
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort  # Exposes the webapp on a NodePort for external access
