apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: webapp
  labels:
    app: employees
spec:
  imagePullSecrets:
    - name: ecr-secret
  containers:
    - name: webapp-container
      image: 069408709901.dkr.ecr.us-east-1.amazonaws.com/myapp-repo:app-v0.1  # Updated ECR Image
      env:
        - name: DBHOST
          value: "mysql-service.mysql-namespace.svc.cluster.local"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "rootpassword"
        - name: DATABASE
          value: "employees"
        - name: DBPORT
          value: "3306"
      ports:
        - containerPort: 8080
