apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp
spec:
  selector:
    app: employees
  ports:
    - protocol: TCP
      port: 80       # Exposes the service on port 80 inside the cluster
      targetPort: 8080  # Forwards traffic to container's port 8080
      nodePort: 30000   # Exposes it externally on NodePort 30000
  type: NodePort

